name: Simple Test

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Always succeed
        run: |
          echo "✅ Проверка пройдена успешно"
          exit 0