name: Unit testing for lab 6

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install pytest pandas opencv-python-headless

    - name: Run tests
      run: |
        cd lab_6
        python -c "import pandas; import cv2; print('Dependencies installed')"
        python -m pytest unit_tests/ -v